### ISSUE TITLE
Headers for source and destination names

### ISSUE THREAD

**Issue by nickmcdowall** [integreety/lsd-distributed-interceptor-library#1]
To simplify the naming of services on the sequence diagrams we could accept header values that specify the target or source names. This can help overcome some of the limitations of the current options (e.g. overloaded path names from multiple services)

For the names something like Target-Name and Source-Name seems to be sensible (The `X-` prefix is now discouraged for custom headers). I don't think we need to add anything to the name that references yatspec or lsd since it's just a generic meta-data that the libraries will happen to use? (what do you think)

The above names match what the (non-distributed) interceptor library currently uses but if we find better names we can change that to be in sync since many projects will use both libs.

**Comment by lukasz-gryzbon** [comment]
Nice one @nickmcdowall ! Thanks1
