### ISSUE TITLE
Include headers when populating the payloads on reports

### ISSUE THREAD

**Issue by nickmcdowall** [integreety/lsd-distributed-interceptor-library#19]
* Request/Response headers would be useful

**Comment by lukasz-gryzbon** [comment]
Examples of added headers:

![image](https://user-images.githubusercontent.com/5703054/126408495-8ed77c3e-7749-4f17-9d3f-6f2ca859bf73.png)

![image](https://user-images.githubusercontent.com/5703054/126408628-c34613eb-37ec-4324-9394-17ba63713bd3.png)

![image](https://user-images.githubusercontent.com/5703054/126408647-408003a4-7d0c-41fe-9885-49adf29f8601.png)

![image](https://user-images.githubusercontent.com/5703054/126408662-242c34d6-4610-4302-bdb0-777b1d80518a.png)

Let me know what you think @nickmcdowall
