### ISSUE TITLE
Mark synchronous responses explicitly

### ISSUE THREAD

**Issue by nickmcdowall** [integreety/lsd-distributed-interceptor-library#23]
Synchronous respones (e.g. http sync responses) can be marked explicitly. This is useful for styling purposes and also be be filtered out from the component diagrams.

For the DSL syntax it just needs the sync keyword as a prefix e.g. 
```
sync response from A to B
```
 or alternatively with the builder e.g.:
```
SynchronousResponse.builder()
    .id(123)
    .label("A synchronous response")
    .from("A")
    .to("B")
    .data("200 OK")
    .build()
`

**Comment by lukasz-gryzbon** [comment]
I'd like to start using the `SequenceEvent` type hierarchy from `lsd-core`, but this is going to take some major refactoring. I have added a new issue for this: #25
