### ISSUE TITLE
Capture Request and Response headers

### ISSUE THREAD

**Issue by nickmcdowall** [integreety/lsd-distributed-interceptor-library#5]
It would be super useful if we could have the request headers available on the response interactions. This is so that the `Source-Name` and `Target-Name` headers are available when we determine the source and destination mappings (since the  headers aren't copied to the response message).

Other options include merging all headers together but that feels a bit dirty and may cause confusion. Storing both sets of headers may even provide additional info for troubleshooting in addition to solving the missing `Source-Name` and `Target-Name` header problem.

**Comment by lukasz-gryzbon** [comment]
👍
