### ISSUE TITLE
Fix LSD diagram for EndToEndIT

### ISSUE THREAD

**Issue by nickmcdowall** [integreety/lsd-distributed-interceptor-library#6]
Some notes for things to fix the diagrams:

* Add missing `@ExtendWith`
* Figure out why some popups aren't working (may be a yatspec bug)
* Why are some interactions missing (or should yatspec handle the missing values better)

**Comment by lukasz-gryzbon** [comment]
For me there was no report generated at all. 

I have added `@ExtendWith(LsdExtension.class)` - this enabled the generation of the report but:
- there is no link to the report in the logs
- there is no diagrams on the report

**Comment by lukasz-gryzbon** [comment]
@nickmcdowall please have a look and advise if possible. I have pushed a small change on the `#6` branch.

**Comment by nickmcdowall** [comment]
Hey man,

Seems it does print out the report url in the logs:

![image](https://user-images.githubusercontent.com/1330362/124979730-550c0a00-e02b-11eb-9b8b-5ea1505ff44f.png)

For the missing diagrams it seems that no interactions are captured in the LsdContext 🤔.. Not sure if that is down to the interceptors or something more tricky like classloaders causing different instances of the context to load.

**Comment by nickmcdowall** [comment]
ah also noticed this is some of the tests:

`doNothing().when(lsdContext).capture(argumentCaptor.capture(), any());`

(Note that if there are no captured events there won't be a diagram)
